---
version: 2
sources:
- name: "kaustubh.default"
  database: "kaustubh"
  schema: "default"
  config:
    enabled: true
  tables:
  - name: "report_table"
    quoting:
      identifier: true
    columns:
    - name: "full_name"
      dataType:
        type: "String"
    - name: "amount"
      dataType:
        type: "Bigint"
    - name: "customer_id"
      dataType:
        type: "Integer"
    type: "table"
